language: php

sudo: false

php:
 - 5.5
 - 5.6
 - 7.0
 - hhvm
 - hhvm-nightly

before_script:
 - ./.travis.install.sh

script:
 - ./vendor/bin/phpunit --configuration=phpunit.travis.xml

matrix:
 allow_failures:
  - php: hhvm
  - php: hhvm-nightly